### ISSUE TITLE
Attributes given back are not correspond with the constants

### ISSUE THREAD

**Issue by vohe** [tomasbedrich/pycaching#159] opened 2020-12-16 07:02 UTC
I (quick)load a cache and print out it's attributes.
May a search for a spechial one, so i compare them against - all the possible attributes. 
But today attributes with the same meaning are changed (on groundspeaks side?)
Here is a workaround i use

```
def changeattribs(Alist):
    otherlist = []
    # groundspeak attrib names are changed?
    # i call Alist = list(cache.attributes.keys())
    # i got  other than
    #  cache._possible_attributes.values()
    # here is a sample of cache.attributes.keys()
    # ['scenic', 'parkngrab', 'bicycles', 'hike_short', 'stealth', 'motorcycles', 'quads', 'jeeps', 'ticks']
    # soo i need to parse that.
    # searching for : ['scenic view']
    # gives me ['scenic']
    for item in Alist:
        if 'wading' in item:
            otherlist.append('wading')
        elif 'stealth' in item:
            otherlist.append('stealth')
        elif 'winter' in item:
            otherlist.append('winter')
        elif 'flashlight' in item:
            otherlist.append('flashlight')
        elif 'stroller' in item:
            otherlist.append('stroller')
        elif 'climbing' in item:
            otherlist.append('climbing')
        elif 'wheelchair' in item:
            otherlist.append('wheelchair')
        elif 'short hike' in item:
            otherlist.append('hike_short')
        elif 'long hike' in item:
            otherlist.append('hike_long')
        elif 'night' in item:
            otherlist.append('night')
        elif 'scenic' in item:
            otherlist.append('scenic')
        else:
            otherlist.append(item)
    return otherlist

```

May that could discribe better , what i mean.
Thanks

**Comment by FriedrichFroebel** [comment] 2020-12-16 08:47
I do not fully understand what the problem is in your case.

`cache.attributes` is a dictionary with the string ID of the attribute as a key and a corresponding boolean value. `cache._possible_attributes` is a dictionary with the string ID of the attribute as a key as well, but with the values being the human-readable attribute title. If you want to search for a specific attribute, just use its string ID, for example `"winter" in cache.attributes`.

If you want to retrieve the attribute titles for the attributes of the selected cache, you could use
```python
titles = [cache._possible_attributes[id_] for id_ in cache.attributes]
```
This won't give you any information on the attribute state, but you could get a similar dictionary as `cache.attributes` with the string IDs replaced by the titles using something like
```python
titles = [cache._possible_attributes[id_] for id_ in cache.attributes]
states = dict(zip(titles, cache.attributes.values()))
```

Is this what you are looking for?

**Comment by vohe** [comment] 2020-12-16 09:14
I want to know if a attribute is set in a cache. Assuming that if there is a attribute set i do not care (at the moment if it is True or False), because of mostly if it is set it is True.
So  in my stupid human thought i do this
```
    attibs = list(cache._possible_attributes.values())
   AttribSearch = # is a sublist of attibs selected by an Listbox from an UI, so it could be:
        ['scenic view',]
    cache = geocaching.get_cache("GC8KG92")
    cache.load_quick()
    print(f'Geocache {cache.name}, has: {list(cache.attributes.keys())}, from: {list(cache._possible_attributes.values())}')
    try:
      list_a = list(cache.attributes.keys())
      print(f'search_in: {list_a}')
      list_b = changeattribs(AttribSearch)
      andlist = set(list_a) & set(list_b)
      notlist = set(list_b) - set(andlist)
```
I want select (human readable) attributes and compare them with the given once in the cache description.
First i only want to know if one of the attributes are in the cache set.
Later i may search for True or False setting (the state of the attribute)

**Comment by vohe** [comment] 2020-12-16 09:30
Here is a executable sample of what i need / want / saw....
```
#!/usr/bin/env python3
"""
This Program should find a buch of caches in a given square of coordinates
"""
import pycaching

name = 'geocacher name'
password = 'geocacher password'

geocaching = pycaching.login(name, password)

cache = geocaching.get_cache("GC8KG92")
attibs = list(cache._possible_attributes.values())
print(attibs)
cache.load_quick()
print(f'Geocache {cache.name}, has: {list(cache.attributes.keys())} \n from: {list(cache._possible_attributes.values())}')
# how could i check that 'scenic' from  list(cache.attributes.keys()) is a possible attribute ?

```

**Comment by FriedrichFroebel** [comment] 2020-12-16 09:48
According to your first comment, you have a list of possible attribute names like `Scenic View` (not string IDs!) which originate from an UI dropdown selection. The `cache.attributes.keys()` list contains string IDs like `scenic`.

You have to transform one of the values to the other type (attribute name <-> attribute string ID) now. I recommend you to convert `cache.attributes.keys()` to attribute names (see `texts` in https://github.com/tomasbedrich/pycaching/issues/159#issuecomment-745931274), as this basically boils down to regular key-based dictionary lookups instead of dictionary value lookups (which only makes sense for bi-diretional dictionaries in my opinion, which we do not have). (Your UI framework might support decoupling the displayed name and returned values for dropdown selections, but this is out of scope here.)

Example (in your code you are loading the geocache twice, which I have removed):
```python
#!/usr/bin/env python3
# -*- coding: utf8 -*-

import pycaching
geocaching = pycaching.login("username", "password")

cache = geocaching.get_cache("GC8KG92")
attribute_names = [cache._possible_attributes[id_] for id_ in cache.attributes]
search_terms = ["Scenic view"]
for term in search_terms:
    print(f"{term}: {term in attribute_names}")
```

**Comment by tomasbedrich** [comment] 2020-12-16 10:25
As a side note: I see `cache._possible_attributes` is used publicly. Should we somehow make it public then? Removing `_` at beginning would be obvious, but we can consider other options as well – maybe having it a static Cache attribute is not the best place to store this.

**Comment by FriedrichFroebel** [comment] 2020-12-16 12:03
@tomasbedrich As cache type, size, status, waypoints already are class-based, we might want to do the same with the attributes. This would allow us to provide the mappings between the string ID and the names (and vice versa) as well, which seems to be the underlying reason for opening this issue as this difference might not be clear.

**Comment by vohe** [comment] 2020-12-17 05:46
Yes you should do that with attributes. It would be more readable to code. 
But: 
> 'According to your first comment, you have a list of possible attribute names like Scenic View (not string IDs!) which originate from an UI dropdown selection. The cache.attributes.keys() list contains string IDs like scenic.
You have to transform one of the values to the other type (attribute name <-> attribute string ID) now. '

I fill the ListView of the Ui with list(cache._possible_attributes.values() . I don't ask (in that time) if that are values or keys, i got human readable strings and thats what i was looking for. - All possible attributes for a user to select.
> 'You have to transform one of the values to the other type (attribute name <-> attribute string ID) now. '
May i could do that, but in the end i only what the user to select which geocaches should be displayed if he decide to search for all of them with Scenic View as (True and/or False).
So i have to compare users selection with the attibs given in cache. 
And the keys of attribute that are set in a cache i only could get with the call of cache.attributes.keys()

And in that case i want (get) two lists (which later may could be dicts) with attributes (-strings) to compare with each other.
My sampe: print(f'Geocache {cache.name}, has: {list(cache.attributes.keys())} \n from: {list(cache._possible_attributes.values())}')

Gives me different strings for the same attribute. As i wrote for 'Scenic View':
Inside  _possible_attibutes.values() it is shown as 'Scenic View' - see it is a readable string not an id or number
and cache.attributes.key() holds (if it is there) 'scenic' - also a readable string but lower case without the word 'View'
and this is not compareble.
So all that is needed, is a array, list, dict,collection what ever, which holds all **possible** keys that could be given from cache.attributes.key() function.

**Comment by FriedrichFroebel** [comment] 2020-12-17 09:03
It seems like we are currently repeating ourselves.

> So all that is needed, is a array, list, dict,collection what ever, which holds all possible keys that could be given from cache.attributes.key() function.

I think you meant to write `cache.attributes.keys()`. As already mentioned, just call `cache._possible_attributes.keys()` for all possible keys (yes, it is marked as a somehow private attribute for now, but this should not be a problem at the moment).

>> You have to transform one of the values to the other type (attribute name <-> attribute string ID) now. 
>
> May i could do that, but in the end i only what the user to select which geocaches should be displayed if he decide to search for all of them with Scenic View as (True and/or False).
> So i have to compare users selection with the attibs given in cache.
> And the keys of attribute that are set in a cache i only could get with the call of cache.attributes.keys()

*pycaching* is a general-purpose Python module for working with the Geocaching.com site. If you decide that the search terms passed to your search function will always be from `cache._possible_attributes.values()`, it is your choice, but then you will have to do the aforementioned transformations. So it basically boils down your application having to handle this conversion itself, which should not be a real problem as can be seen in my example code from https://github.com/tomasbedrich/pycaching/issues/159#issuecomment-746003785 which implements this search functionality by adapting `cache.attributes.keys()`.

**Comment by FriedrichFroebel** [comment] 2022-02-24 20:11
As I do not think that there is something wrong on the *pycaching* side here, I am going to close this issue for now. The list of available attributes and their future implementation is tracked in #160 already.

**Closed by FriedrichFroebel** 2022-02-24 20:11 UTC
Labels: support request
