### ISSUE TITLE
searching my_owned

### ISSUE THREAD

**Issue by Aslang13** [tomasbedrich/pycaching#198] opened 2022-11-17 10:25 UTC
hay. I am some what new to the community.
i hope this feature request  is cool
the geocaching has a my_finds option
since the search does not work is it possible to add to it in some way a "my_owned" feture?

**Comment by FriedrichFroebel** [comment] 2022-11-17 10:30
This seems to be a duplicate of #148.

**Closed** 2023-01-14 19:37 UTC
