### ISSUE TITLE
Error raise while log a TB

### ISSUE THREAD

**Issue by vohe** [tomasbedrich/pycaching#130] opened 2020-01-12 19:12 UTC
Hi, as i use in my python file

```
trackable = geocaching.get_trackable(x)
print(trackable.name, trackable.goal, trackable.description, trackable.location)
log = Log(type=LogType.discovered_it, text=logtext, visited=datetime.date.today())
tracking_code = x
trackable.post_log(log, tracking_code)
```
it raises an error like:

```
Traceback (most recent call last):
  File ".../main.py", line 95, in <module>
    main()
  File ".../main.py", line 86, in main
    trackable.post_log(log, tracking_code)
  File "...\venv\lib\site-packages\pycaching\trackable.py", line 242, in post_log
    formatted_date = format_date(log.visited, date_format)
  File ...\venv\lib\site-packages\pycaching\util.py", line 91, in format_date
    return date.strftime(date_format)
ValueError: Invalid format string
```

Tested under: 
Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 22:39:24) [MSC v.1916 32 bit (Intel)]

i make a change to get it work in `util.py` i do:

```
def format_date(date, user_date_format):
    """Format a date according to user_date_format."""
    # parse user format
    date_format = user_date_format.lower()
    date_format = re.split("(\W+)", date_format)
    formats = {
        "dd": r'%d',
        "d": r'%-d',
        "mmm": r'%b',
        "mm": r'%m',
        "m": r'%-m',
        "yyyy": r'%Y',
        "yy": r'%y',
    }
    date_format = "".join((formats[c] if c in formats else c for c in date_format))
    if not type(date_format) == str:
        return date.strftime(date_format)
    else:
        return date_format
```

that works for me.
please excuse the long post, i am not familiar with this.

**Comment by FriedrichFroebel** [comment] 2020-01-12 20:19
Thanks for reporting. I am not able to reproduce this problem and I do not think that your proposed fix should be applied as-is.  (As far as I can see, the site redesign has not yet been affecting the TB log page in my case.)

As you have already modified the `pycaching.util.format_date` method: Could you please check what the content of `user_date_format` is by printing it during a quick test?

**Comment by vohe** [comment] 2020-01-12 20:51
I could only report this problem under windows10 installed the latest version of python, the same code under Linux doesn't stops. 
But now, yours please:
As i insert a print commad (see below) i get this print out:

User_date_format Type <class 'str'> and Content d.M.yyyy

--- code
```
def format_date(date, user_date_format):
    """Format a date according to user_date_format."""
    # insert a debugging print command
    print('User_date_format Type {} and Content {}'.format(type(user_date_format),user_date_format))
    # parse user format
    date_format = user_date_format.lower()
    date_format = re.split("(\W+)", date_format)
    formats = {
        "dd": r'%d',
        "d": r'%-d',
        "mmm": r'%b',
        "mm": r'%m',
        "m": r'%-m',
        "yyyy": r'%Y',
        "yy": r'%y',
    }
    date_format = "".join((formats[c] if c in formats else c for c in date_format))
    if not type(date_format) == str:
        return date.strftime(date_format)
    else:
        return date_format
```
---

and i guess it's another output under linux (which the same code doesn't raise an error)
Thanks for reply.

**Comment by vohe** [comment] 2020-01-12 20:57
Oh, and may you want to know what the join command is doing with this ? I ad another line in front of my if/else statement.

if i do that:
```
    date_format = "".join((formats[c] if c in formats else c for c in date_format))
    # another output for debug.
    print('date_format Type {} and Content {}'.format(type(date_format),date_format))
    if not type(date_format) == str:

```
i got:
User_date_format Type <class 'str'> and Content d.M.yyyy
date_format Type <class 'str'> and Content %-d.%-m.%Y

**Comment by FriedrichFroebel** [comment] 2020-01-13 06:15
This sounds like some problem regarding `datetime` on Windows systems with specific date formats shown on the geocaching website. According to https://strftime.org/ the `-` flag in front of a regular specifier is platform-dependent, so we should probably try to fix this problem.

As far as I can see, your fix is incorrect - the type of `date_format` should always be a string, so the first case of the if statement will never be executed. The else branch of the statement does not match the requirements of the `format_date` method as instead of formatting a given date, it returns a format string.

**Comment by FriedrichFroebel** [comment] 2020-01-13 13:22
In your case, a correct fix would probably be to replace the return statement of the `format_date` method with the following snippet which provides some sort of custom implementation of the `-` flag:

```python
    try:
        return date.strftime(date_format)
    except ValueError:
        date_format = date_format.replace("%-d", str(date.day))
        date_format = date_format.replace("%-m", str(date.month))
        return date.strftime(date_format)
```

**Closed** 2020-01-17 08:56 UTC

**Comment by tomasbedrich** [comment] 2020-01-17 09:11
New release 4.0.1 is published with fix. Please try that and let us know.

**Comment by vohe** [comment] 2020-01-17 15:35
Done, fix works as expected. I checked it under Windows10 / Python 3.7 and 3.8 and Linux (Ubuntu 19.10... Pyhton 3.7).
Thanks for this.
